export const BOOKS_PAGE = 'BOOKS_PAGE';
export const BOOK_DETAILS_PAGE = 'BOOK_DETAILS_PAGE';
export const AUTHORS_PAGE = 'AUTHORS_PAGE';
export const AUTHOR_DETAILS_PAGE = 'AUTHOR_DETAILS_PAGE';
export const GENRES_PAGE = 'GENRES_PAGE';
export const GENRE_BOOKS_PAGE = 'GENRE_BOOKS_PAGE';
export const MAIN_PAGE = 'MAIN_PAGE';
